### ISSUE TITLE
map reduction

### ISSUE THREAD

**Issue by saimanojj** [andreaiacono/MapReduce#1]
how can we access a word document by using map reduction

**Comment by andreaiacono** [comment]
There's a nice library from Apache called POI ( https://poi.apache.org/ ) which allows you to parse Microsoft Office formats; you could extend FileInputFormat class using this library (but I don't know if POI gives you all the info needed to extend FileInputFormat); another option is to transform in plain text files all the word documents you have (always using POI) and then treat them as a normal input for MapReduce.

**Comment by saimanojj** [comment]
Can u share sample code?

-----Original Message-----

**Comment by andreaiacono** [comment]
Sorry, I never had to deal with Microsoft formats, so no code to share..
