### ISSUE TITLE
how  can I run the KMeans ?

### ISSUE THREAD

**Issue by fanrongqitiancai** [andreaiacono/MapReduce#2]
I run this project on eclipse , java 1.8  .when I run the project ,it show me the info :
Usage: KMeans <in> <out> <clusters_number>

how to config this code ? thank you .

**Comment by andreaiacono** [comment]
It's asking how many clusters you want to divide your data into. You should add this number as a program argument; I don't know how to do it in Eclipse (I use IntelliJ), but you con google for `eclipse add program argument` and find out how.

**Comment by fanrongqitiancai** [comment]
sorry ,I can not understand ,Should the parameter be a file?
```
KMeans <in> <out> <clusters_number>
```
I must set the parameter like 
in:resources\kmeans
thank you very much.

**Comment by fanrongqitiancai** [comment]
when I run in IntelliJ   ,the info is 
```
Process finished with exit code -2
Empty test suite.
```
I need to config the project?
thank you .
