### ISSUE TITLE
Do I need to install hadoop?

### ISSUE THREAD

**Issue by fanrongqitiancai** [andreaiacono/MapReduce#4]
Do I need to install hadoop?  [hadoop](http://hadoop.apache.org/releases.html)

**Comment by andreaiacono** [comment]
yes, definitely. At the time of writing this demo project, I also wrote some blog posts for installing and running mapreduce. You can find them here:
http://andreaiacono.blogspot.com/2014/02/installing-hadoop-220-on-ubuntu.html
http://andreaiacono.blogspot.com/2014/02/running-hadoop-example.html

They refer to a very old version of Hadoop, you may find something newer and adapt the code to it.
