### ISSUE TITLE
Slides not accessible

### ISSUE THREAD

**Issue by Shajeel-Afzal** [andreaiacono/MapReduce#5]
Hi, 

Thanks for sharing. Looks like your slides are not accessible now. Also, can you please share the link of the video if available?

Regards
Shajeel

**Comment by andreaiacono** [comment]
Hi Shajeel,
somehow Slideshare lost my presentation! I've uploaded it again and updated the README: you can follow the new link to get there.
The video is available at https://www.youtube.com/watch?v=e5KwFbLJVxw but it's in Italian, sorry. 

Cheers,
Andrea
