### ISSUE TITLE
Suggestion to add an open-source license

### ISSUE THREAD

**Issue by SaurabSS** [andreaiacono/MapReduce#6]
Hi,

Thanks you for sharing this awesome repo with many insightful MapReduce programs. Can you please add an open-source license for free use and sharing (for academic purposes), if you intend to make it open-source? 

Alternatively, can you permit me to use the [EnhancedTopN.java](https://github.com/andreaiacono/MapReduce/blob/master/src/main/java/samples/topn_enhanced/EnhancedTopN.java) for academic purposes (modifying and experimenting on large datasets for analysis)? I am working on a project inspecting its run-time scaling.

Best,
Saurab

**Comment by andreaiacono** [comment]
Hi Saurab,
you're right, I definitely meant this repo to be open-source (that's why I published it publicly on github) but I didn't add any license. So, feel free to do whatever you prefer with this code! :-) 
And good luck with your academic research!

Cheers,
Andrea
